<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Plain PHP website</title>
    </head>

    <body>
        <h1>Plain PHP website</h1>

        <p>
            Hello, this is a plain PHP website. The date below is generated by PHP.
        </p>

        <strong><?= date('Y m D') ?></strong>
    </body>
</html>