services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8003:80"
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf